// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnMAIjZO_Z0OQiWJj9OHvptN7yCC3UYn8',
    appId: '1:918758802263:web:8772c83f8a96c57637b412',
    messagingSenderId: '918758802263',
    projectId: 'app-tram-doc',
    authDomain: 'app-tram-doc.firebaseapp.com',
    storageBucket: 'app-tram-doc.firebasestorage.app',
    measurementId: 'G-N14ZQG0Y76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOmKrccYRQ8RFMeXIIWz2aGxWF6xsEbJk',
    appId: '1:918758802263:android:aee1e5d3ed302f6337b412',
    messagingSenderId: '918758802263',
    projectId: 'app-tram-doc',
    storageBucket: 'app-tram-doc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1gYgndVJo4JSBcPzT9LIAwvDq6glacEE',
    appId: '1:918758802263:ios:ef2df92574ec8ab137b412',
    messagingSenderId: '918758802263',
    projectId: 'app-tram-doc',
    storageBucket: 'app-tram-doc.firebasestorage.app',
    iosBundleId: 'com.example.readingStationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1gYgndVJo4JSBcPzT9LIAwvDq6glacEE',
    appId: '1:918758802263:ios:ef2df92574ec8ab137b412',
    messagingSenderId: '918758802263',
    projectId: 'app-tram-doc',
    storageBucket: 'app-tram-doc.firebasestorage.app',
    iosBundleId: 'com.example.readingStationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnMAIjZO_Z0OQiWJj9OHvptN7yCC3UYn8',
    appId: '1:918758802263:web:f92cf6614ea2cbee37b412',
    messagingSenderId: '918758802263',
    projectId: 'app-tram-doc',
    authDomain: 'app-tram-doc.firebaseapp.com',
    storageBucket: 'app-tram-doc.firebasestorage.app',
    measurementId: 'G-QXFGXHRF7E',
  );
}
